<?php 
/*
Copyright 2010 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

require_once("ui.inc");
require_once("utils.inc");

$gTitle = "Downloads";

function listFiles($hFiles) {
	$sHtml = "";
	$aKeys = array_keys($hFiles);
	sort($aKeys, SORT_NUMERIC);
	foreach( array_reverse($aKeys) as $epoch ) {
		$filename = $hFiles[$epoch];
		$label = date("M j, Y", $epoch);
		$filesize = filesize($filename);
		$size = ( $filesize > 1024*1024 ? round($filesize/(1024*1024)) . " MB" : round($filesize/(1024)) . " kB" );
		$sHtml .= "  <li> <a href='$filename'>$label</a> ($size)\n";
	}

	return $sHtml;
}
?>
<!doctype html>
<html>
<head>
<title><?php echo $gTitle ?></title>
<meta charset="UTF-8">

<?php echo headfirst() ?>
<link type="text/css" rel="stylesheet" href="style.css" />
</head>

<body>

<?php echo uiHeader($gTitle); ?>
<h1>Downloads</h1>

<?php
$desktopFiles = array();
$mobileFiles = array();
foreach ( glob("downloads/httparchive_*.gz") as $filename ) {
	$epoch = dumpfileEpochTime($filename);
	if ( $epoch ) {
		if ( FALSE ===  strpos($filename, "httparchive_mobile_") ) {
			$desktopFiles[$epoch] = $filename;
		}
		else {
			$mobileFiles[$epoch] = $filename;
		}
	}
}
?>

<p>
There's a download file for each run:
</p>

<style>
.indent LI { margin-bottom: 2px; }
</style>

<strong>HTTP Archive (desktop):</strong>

<ul class=indent>
<?php echo listFiles($desktopFiles) ?>
</ul>

<strong>HTTP Archive Mobile:</strong>
<ul class=indent>
<?php echo listFiles($mobileFiles) ?>
</ul>

<p>
The downloaded file was generated by <a href="http://dev.mysql.com/doc/refman/5.1/en/mysqldump.html">mysqldump</a> and then gzipped.
The mysqldump file does <em>not</em> contain the commands to create the MySQL database and tables.
To restore these mysqldump downloads:
</p>

<ol class=indent>
  <li> Install the <a href="http://code.google.com/p/httparchive/source/checkout">HTTP Archive source code</a>.
  <li> Modify <code>settings.inc</code> to have the appropriate MySQL settings.
  <li> Open the <code>admin.php</code> page in your browser and click on the link to create the MySQL tables.
  <li> Ungzip the downloaded mysqldump file.
  <li> Import the mysqldump file using this command:<br><code>mysql -v -u MYSQL_USERNAME -pMYSQL_PASSWORD -h MYSQL_HOSTNAME MYSQL_DB < MYSQLDUMP_FILE</code>
</ol>

<?php echo uiFooter() ?>

</body>

</html>

