<?php 
/*
Copyright 2010 Google Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

require_once("ui.php");
require_once("utils.php");

$gTitle = "News";
?>
<!doctype html>
<html>
<head>
	<link type="text/css" rel="stylesheet" href="style.css" />
	
	<title><?php echo $gTitle ?></title>
	<meta charset="UTF-8">

<style>
DT { font-weight: bold; margin-top: 20px; }
DD { margin-left: 40px; }
</style>
</head>

<body>

<?php echo uiHeader($gTitle); ?>
<h1><?php echo $gTitle ?></h1>

<dl id=news>
  <dt> March 21, 2011: har_to_pagespeed updated
  <dd> har_to_pagespeed was updated from version 1.7 to 1.9. 
<p>
Several new rules were added and some were removed.
Page Speed reports shown for individual websites use the latest version of har_to_pagespeed.
This is true for all websites regardless of the data selected because that date's HAR file is fed
to the latest version of har_to_pagespeed.
</p>
<p>
The trending charts, however, are based on Page Speed scores generated by the version of har_to_pagespeed
in use at that time.
Therefore, there may be differences between the Page Speed scores from trending data as compared to the detailed Page Speed report.
For now we'll leave the old trending data as is. 
It may prove interesting to see how the expectation of tools like Page Speed change over time.
If later it's decided that all scores should be based on the latest version of har_to_pagespeed 
we'll update the scores in batch at that time.
</p>
</dl>


<?php echo uiFooter() ?>

</body>

</html>

